source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LayoutComposer_Example', :exclusive => true do
  pod "LayoutComposer", :path => "../"
end

target 'LayoutComposer_Tests', :exclusive => true do
  pod "LayoutComposer", :path => "../"

  
end
